version: 2

sources:

    - name: dbgen
      database: dbt
      schema: dbt
      tags: ["dbgen"]
      loader: S3
      description: "External tables"

      tables:

        - name: customer
          description: "List of customers in S3 bucket"
          identifier: src_customer

        - name: lineorder
          description: "Fact table in S3 bucket"
          identifier: src_lineorder

        - name: part
          description: "List of parts in S3 bucket"
          identifier: src_part

        - name: supplier
          description: "List of suppliers in S3 bucket"
          identifier: src_supplier